<#import "parts/common.ftlh" as c>
<#import 'parts/login.ftlh' as l>


<@c.page>
    <div class="jumbotron">
        <h1 class="display-4">Здраствуй Гость</h1>
        <p class="lead">Это мини приложение для конвертации валют по котировкам Центрального Банка России.</p>
        <hr class="my-4">
        <a href="/registration">Регистрация</a><br>
        <a href="/main">Вход</a>
    </div>

</@c.page>